import type { Metadata } from "next";
import Header from "@/components/header/Header";
import SidebarHomestayOwner from "@/components/sidebar/SidebarHomestayOwner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-roboto antialiased `}>
        <Header />
        <div className="flex w-full">
          <div className="w-[20%] min-h-screen bg-gray-100 shadow-md py-4 px-2">
            <SidebarHomestayOwner />
          </div>

          <div className="w-[80%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
