import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import { AuthProvider } from "./contexts/AuthContext";
import { CheckoutProvider } from "./contexts/CheckoutContext";
import { ReservationProvider } from "./contexts/ReservationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <CheckoutProvider>
          <ReservationProvider>
            <body className={`font-roboto antialiased `}>
              <Header />
              <div>{children}</div>
            </body>
          </ReservationProvider>
        </CheckoutProvider>
      </AuthProvider>
    </html>
  );
}
